#!/bin/bash/env bash

# Get the list of network interfaces
interfaces=$(ip -o -4 addr show | awk '{print $2}')

# Loop through the interfaces
for interface in $interfaces; do
  # Get the IPv4 address for each interface
  ipv4=$(ip -o -4 addr show $interface | awk '{print $4}' | cut -d/ -f1)
  # Print the IPv4 address
  echo $ipv4
done
